### ISSUE TITLE
No RSS feed

### ISSUE THREAD

**Issue by Stantheman** [joshuarli/jrl.ninja#1]
Hi! Loved your glibc vs musl `getaddrinfo` post! Could you generate a feed please?

**Comment by pixelbly** [comment]
Yes, a feed is needed.

**Comment by joshuarli** [comment]
Hi, this slipped under my radar. Thanks for the compliment! Although, I feel like this would be more trouble than it's worth; I don't post a lot/often and currently unsure if there are any good + minimal rss feed generators out there since I'm completely decoupled with static site generators that typically include that kind of stuff.
